export const dummyResources = [
  {
    title: "DBMS Unit 3 - Normalization Notes",
    subject: "Database Management Systems",
    type: "notes",
    university: "RTMNU",
    branch: "Computer Science",
    semester: 5,
    uploadedBy: "Ananya S.",
    fileURL: "https://placeholder.com/file.pdf",
    downloads: 128,
  },
  {
    title: "Operating Systems End Sem Question Paper 2025",
    subject: "Operating Systems",
    type: "question paper",
    university: "RTMNU",
    branch: "Computer Science",
    semester: 4,
    uploadedBy: "Rohit K.",
    fileURL: "https://placeholder.com/file.pdf",
    downloads: 342,
  },
  {
    title: "Introduction to Algorithms (CLRS) - Full Textbook",
    subject: "Data Structures & Algorithms",
    type: "textbook",
    university: "RTMNU",
    branch: "Computer Science",
    semester: 3,
    uploadedBy: "Priya M.",
    fileURL: "https://placeholder.com/file.pdf",
    downloads: 891,
  },
  {
    title: "A Survey on Transformer Architectures in NLP",
    subject: "Machine Learning",
    type: "research paper",
    university: "RTMNU",
    branch: "Computer Science",
    semester: 7,
    uploadedBy: "Dr. Verma",
    fileURL: "https://placeholder.com/file.pdf",
    downloads: 56,
  },
  {
    title: "Computer Networks Unit 1-5 Notes (Handwritten)",
    subject: "Computer Networks",
    type: "notes",
    university: "RTMNU",
    branch: "Computer Science",
    semester: 5,
    uploadedBy: "Shreya T.",
    fileURL: "https://placeholder.com/file.pdf",
    downloads: 204,
  },
];